# Pipeline completo: YOLO → OCR → Parse
name: expiry_date_full_pipeline

# Detecção (YOLO)
detection:
  model_path: experiments\1104\yolov8m-seg\weights\best.pt
  confidence: 0.25
  iou: 0.7
  device: 0

# OCR
ocr:
  engine: openocr
  config: config/ocr/openocr.yaml
  preprocessing: config/preprocessing/ppro-openocr.yaml